### ISSUE TITLE
Crash on clear when running in Git Bash Console (not when using built in terminal in VSCode with Git Bash

### ISSUE THREAD

**Issue by AzFoxxo** [AzFoxxo/AzzyShell#1]
Unhandled exception on "clear" command causing crash.
```
Unhandled exception. System.IO.IOException: The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.Clear()
   at System.Console.Clear()
   at App.Commands.Clear.Execute(String[] args) in A:\dev\csharp\AzzyShell\heroes\app\commands\Clear.cs:line 13
   at App.AzzyShell.CommandSwitch() in A:\dev\csharp\AzzyShell\heroes\app\AzzyShell.cs:line 189
   at App.AzzyShell.OnUpdate() inAD:\dev\csharp\AzzyShell\heroes\app\AzzyShell.cs:line 112
   at Heroes.Internal.GameLoop.Enter() in A:\dev\csharp\AzzyShell\heroes\heroes\internal\GameLoop.cs:line 24
   at Heroes.Internal.Program.Main(String[] args) in A:\dev\csharp\AzzyShell\heroes\heroes\internal\Entry.cs:line 9
```

**Comment by AzFoxxo** [comment]
Problem cannot be fixed so catching error and informing the user.
